[package]
name = "svc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bitflags = "2.4.2"
wit-bindgen-rt = "0.22.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target = { path = "../service.wit",  world = "service" }

[workspace]
